name: Deno

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - uses: straw-hat-team/github-actions-workflows/asdf/get-version@master
        id: deno-version
        name: Get Deno version from .tool-versions
        with:
          plugin-name: deno

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v${{ steps.deno-version.outputs.plugin-version }}

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A --unstable
