name: Deno

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - uses: straw-hat-team/github-actions-workflows/asdf/get-version@5ab906d801d41b723636b498e57509e18db1856a # v1.9.1
        id: deno-version
        name: Get Deno version from .tool-versions
        with:
          plugin-name: deno

      - name: Setup Deno
        uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d # v1.5.2
        with:
          deno-version: v${{ steps.deno-version.outputs.plugin-version }}

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A --unstable
